### ISSUE TITLE
Failing to compile after applying plugin

### ISSUE THREAD

**Issue by peppercat10** [deepmedia/Grease#1] opened 2021-09-28 13:22 UTC
Hi. I'm trying to use Grease on a default KMM project. Once I apply the plugin and sync, I get the following error:

`Caused by: java.lang.NoSuchMethodError: 'org.gradle.api.file.FileCollection com.android.build.gradle.internal.tasks.MergeFileTask.getInputFiles()'`

Do you have any idea what might be happening?
Thanks

**Comment by peppercat10** [comment] 2021-09-28 13:38
Gradle version: 7.0.2
Stacktrace: https://gist.github.com/peppercat10/795488d9663082c81f8d8a325e4fd0b6

Thanks for looking into this!

**Comment by DastanIqbal** [comment] 2022-12-14 21:11
Facing same issue 
`Caused by: java.lang.NoSuchMethodError: 'org.gradle.api.file.FileCollection com.android.build.gradle.internal.tasks.MergeFileTask.getInputFiles()'
	at io.deepmedia.tools.grease`

**Comment by natario1** [comment] 2024-08-25 18:19
Should be fixed in latest version.

**Closed by natario1** 2024-08-25 18:19 UTC
